import type { Brand } from "./types";

/**
 * Datos base que se usan solo cuando Supabase no esta configurado o no responde.
 * Mantienen la interfaz visible durante el desarrollo local sin romper la aplicacion.
 */
export const fallbackBrands: Brand[] = [
    {
        id: "br-001",
        name: "Aura Verde",
        category: "Ropa Deportiva",
        slogan: "Movimiento organico",
        description: "Ropa deportiva de alto rendimiento confeccionada con plasticos oceanicos recuperados y tintes naturales. Transparencia total en su cadena de suministro.",
        overallRating: "Genial",
        asgScores: { ambiental: 5, social: 4, gobernanza: 5 },
        imageUrl: "/img/moodboard-1.jpg",
        isVegan: true,
        isFairTrade: true,
        materials: ["PET Reciclado", "Algodon Organico"],
    },
    {
        id: "br-002",
        name: "Lino & Tierra",
        category: "Casual",
        slogan: "Lo clasico perdura",
        description: "Basicos atemporales de lino cultivado en Europa. Excelentes condiciones laborales y un enfoque claro hacia el residuo cero en sus talleres.",
        overallRating: "Genial",
        asgScores: { ambiental: 4, social: 5, gobernanza: 5 },
        imageUrl: "/img/moodboard-2.jpg",
        isVegan: true,
        isFairTrade: true,
        materials: ["Lino Europeo"],
    },
    {
        id: "br-003",
        name: "Urban Fast",
        category: "Streetwear",
        slogan: "A la velocidad de la ciudad",
        description: "Moda rapida y de tendencia constante. Frecuentes rotaciones de catalogo y escasa transparencia respecto al origen y fin de vida de sus materiales.",
        overallRating: "Evitar",
        asgScores: { ambiental: 1, social: 2, gobernanza: 1 },
        imageUrl: "/img/moodboard-3.jpg",
        isVegan: false,
        isFairTrade: false,
        materials: ["Poliester", "Acrilico"],
    },
    {
        id: "br-004",
        name: "Knit Origin",
        category: "Punto",
        slogan: "Tejiendo comunidad",
        description: "Prendas de punto elaboradas por cooperativas de artesanas certificadas. Buen desempeno en derechos laborales, aunque con una politica ambiental moderada.",
        overallRating: "Bueno",
        asgScores: { ambiental: 3, social: 4, gobernanza: 4 },
        imageUrl: "/img/moodboard-1.jpg",
        isVegan: false,
        isFairTrade: true,
        materials: ["Lana Merina", "Alpaca"],
    },
    {
        id: "br-005",
        name: "Essential Co.",
        category: "Basicos",
        slogan: "Lo de siempre",
        description: "Marca de basicos accesibles. Prometen el uso de algodon organico, pero no proporcionan certificaciones verificables sobre sus practicas sociales o de gobernanza.",
        overallRating: "Regular",
        asgScores: { ambiental: 3, social: 2, gobernanza: 2 },
        imageUrl: "/img/moodboard-2.jpg",
        isVegan: true,
        isFairTrade: false,
        materials: ["Algodon Organico Mezclado"],
    },
];
